FROM python:3.11-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        curl \
        build-essential \
        gcc \
        python3-dev \
    && rm -rf /var/lib/apt/lists/*

# Installe Poetry
RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH="/root/.local/bin:$PATH"

# Définit le répertoire de travail
WORKDIR /api_app

# Désactive la création de venv par Poetry
RUN poetry config virtualenvs.create false

# Copie les fichiers de dépendances en premier pour profiter du cache Docker
COPY pyproject.toml poetry.lock ./

# Installe les dépendances du projet en utilisant le lock file.
RUN poetry install --no-interaction --no-ansi --no-root
RUN pip install playsound==1.3.0

RUN pip install torch==2.2.2+cu121 torchvision==0.17.2+cu121 torchaudio==2.2.2+cu121 \
  --index-url https://download.pytorch.org/whl/cu121

# Copie le code de l'application
COPY ./api_app /api_app

EXPOSE 8000

# Lance l'application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
