services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: fast_api_app_container
    ports:
      - "8000:8000"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    networks:
      - eula_net

  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    container_name: django_app_container
    ports:
      - "8001:8001"
    depends_on:
      - fastapi
    environment:
      - GROQ_API_KEY=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
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    networks:
      - eula_net

  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - django
    networks:
      - eula_net

networks:
  eula_net:
    driver: bridge
