FROM python:3.11-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        curl \
        build-essential \
        gcc \
        python3-dev \
        pkg-config \
        libglib2.0-dev \
        libcairo2-dev \
        ffmpeg \
        libgirepository1.0-dev \
        gir1.2-gtk-3.0 \
    && rm -rf /var/lib/apt/lists/*

# Installe Poetry
RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH="/root/.local/bin:$PATH"

# Définit le répertoire de travail
WORKDIR /django_app

# Désactive la création de venv par Poetry
RUN poetry config virtualenvs.create false

# Copie les fichiers de dépendances en premier pour profiter du cache Docker
COPY pyproject.toml poetry.lock ./

# Installe les dépendances du projet en utilisant le lock file.
RUN poetry install --no-interaction --no-ansi --no-root
# RUN pip install playsound==1.3.0 pygobject
RUN pip install playsound==1.3.0

RUN pip install torch==2.2.2+cu121 torchvision==0.17.2+cu121 torchaudio==2.2.2+cu121 \
  --index-url https://download.pytorch.org/whl/cu121

# Patch nécessaire : certaines versions de TTS nécessitent kwargs["weights_only"] pour torch.load
RUN sed -i '/is_local = os.path.isdir(path) or os.path.isfile(path)/a \    kwargs["weights_only"] = False' \
    /usr/local/lib/python3.11/site-packages/TTS/utils/io.py

# Copie le code de l'application
COPY ./django_app /django_app
COPY ./django_entrypoint.sh /django_entrypoint.sh
COPY ./django_app/model /django_app/model

RUN mkdir -p /root/.local/share/tts/tts_models--multilingual--multi-dataset--xtts_v2/
COPY ./django_app/model/xtts_v2/ /root/.local/share/tts/tts_models--multilingual--multi-dataset--xtts_v2/

EXPOSE 8001

RUN chmod +x /django_entrypoint.sh

ENTRYPOINT ["/django_entrypoint.sh"]
