# Generated by Django 5.2.3 on 2025-06-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_to_translate', models.TextField()),
                ('translate_text', models.TextField()),
                ('model_type', models.CharField(choices=[('mBart', 'mBart'), ('API', 'API'), ('opus', 'opus')], max_length=124)),
            ],
        ),
    ]
